/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author francisco.perdomo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        bIngreso = new javax.swing.JButton();
        bdenuncia = new javax.swing.JButton();
        bbuscar = new javax.swing.JButton();
        bregper = new javax.swing.JButton();
        iper = new javax.swing.JLabel();
        imas = new javax.swing.JLabel();
        ibus = new javax.swing.JLabel();
        iden = new javax.swing.JLabel();
        lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setMaximumSize(new java.awt.Dimension(400, 320));
        Fondo.setMinimumSize(new java.awt.Dimension(400, 320));
        Fondo.setPreferredSize(new java.awt.Dimension(400, 320));
        Fondo.setRequestFocusEnabled(false);
        Fondo.setLayout(null);

        Titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 78, 150));
        Titulo.setText("Menu");
        Fondo.add(Titulo);
        Titulo.setBounds(80, 30, 110, 50);

        bIngreso.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bIngreso.setText("Ingresar Mascota");
        bIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresoActionPerformed(evt);
            }
        });
        Fondo.add(bIngreso);
        bIngreso.setBounds(50, 110, 140, 20);

        bdenuncia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bdenuncia.setText("Hacer Denuncia");
        bdenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdenunciaActionPerformed(evt);
            }
        });
        Fondo.add(bdenuncia);
        bdenuncia.setBounds(50, 150, 140, 20);

        bbuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bbuscar.setText("Buscar Mascota");
        bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarActionPerformed(evt);
            }
        });
        Fondo.add(bbuscar);
        bbuscar.setBounds(50, 190, 140, 20);

        bregper.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bregper.setText("Registrar Persona");
        bregper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregperActionPerformed(evt);
            }
        });
        Fondo.add(bregper);
        bregper.setBounds(50, 230, 140, 20);

        iper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/persona.jpg"))); // NOI18N
        Fondo.add(iper);
        iper.setBounds(200, 230, 20, 20);

        imas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pata.jpg"))); // NOI18N
        Fondo.add(imas);
        imas.setBounds(200, 110, 20, 20);

        ibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        Fondo.add(ibus);
        ibus.setBounds(200, 190, 20, 20);

        iden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exclamacion.jpg"))); // NOI18N
        Fondo.add(iden);
        iden.setBounds(200, 150, 20, 20);

        lfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuFondo.jpg"))); // NOI18N
        Fondo.add(lfondo);
        lfondo.setBounds(0, 0, 400, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresoActionPerformed
        new IngresoMascota().setVisible(true);
    }//GEN-LAST:event_bIngresoActionPerformed

    private void bdenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdenunciaActionPerformed
        new Denuncia().setVisible(true);
    }//GEN-LAST:event_bdenunciaActionPerformed

    private void bbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarActionPerformed
        new BuscarMascota().setVisible(true);
    }//GEN-LAST:event_bbuscarActionPerformed

    private void bregperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregperActionPerformed
        new RegistrarPersona().setVisible(true);
    }//GEN-LAST:event_bregperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton bIngreso;
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton bdenuncia;
    private javax.swing.JButton bregper;
    private javax.swing.JLabel ibus;
    private javax.swing.JLabel iden;
    private javax.swing.JLabel imas;
    private javax.swing.JLabel iper;
    private javax.swing.JLabel lfondo;
    // End of variables declaration//GEN-END:variables
}
