
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author francisco.perdomo
 */
public class SubirImagen extends javax.swing.JFrame {
    int idMascota=0;
    
    public SubirImagen() {
        initComponents();
    }
    public SubirImagen(int idm) {
        initComponents();
        idMascota = idm;
        idlabel.setText(idm+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        subir = new javax.swing.JToggleButton();
        imagen1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        lIDMascota = new javax.swing.JLabel();
        listo = new javax.swing.JLabel();
        lFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Fondo.setLayout(null);

        subir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        subir.setText("Subir imagen");
        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });
        Fondo.add(subir);
        subir.setBounds(73, 270, 110, 23);

        imagen1.setBackground(new java.awt.Color(255, 255, 255));
        imagen1.setText("      ");
        imagen1.setMaximumSize(new java.awt.Dimension(200, 200));
        imagen1.setMinimumSize(new java.awt.Dimension(200, 200));
        Fondo.add(imagen1);
        imagen1.setBounds(20, 50, 200, 200);

        Titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 78, 150));
        Titulo.setText("Subir Foto de Mascota");
        Fondo.add(Titulo);
        Titulo.setBounds(10, 20, 230, 21);

        idlabel.setText("     ");
        Fondo.add(idlabel);
        idlabel.setBounds(290, 294, 90, 20);

        lIDMascota.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lIDMascota.setText("ID Mascota:");
        Fondo.add(lIDMascota);
        lIDMascota.setBounds(220, 300, 70, 14);

        listo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listo.setForeground(new java.awt.Color(0, 255, 51));
        listo.setText("        ");
        Fondo.add(listo);
        listo.setBounds(200, 270, 150, 17);

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuFondo.jpg"))); // NOI18N
        lFondo.setText("   ");
        Fondo.add(lFondo);
        lFondo.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(imagen1);
        try {
            Connection con = null;
            Class.forName("org.postgresql.Driver").newInstance();
            // Obtiene una conexión a la base de datos
            con = DriverManager.getConnection("jdbc:postgresql://192.168.56.101:5432/postgres","postgres","a");
            if (!con.isClosed()){
                System.out.println("Successfully connected to MySQL server using TCP/IP...");
            }

            File file = fc.getSelectedFile();
            FileInputStream fis = new FileInputStream(file);
            PreparedStatement ps = con.prepareStatement("INSERT INTO imagen VALUES ("+idMascota+", ?)");
            ps.setBinaryStream(1, fis, (int)file.length());
            ps.executeUpdate();
            ps.close();
            PreparedStatement ps2 = con.prepareStatement("SELECT imagen FROM imagen WHERE id = "+idMascota);
            //ps.setString(2, "perro.jpg");
            ResultSet rs = ps2.executeQuery();
            while (rs.next()) {
                byte[] imgBytes = rs.getBytes(1);
                imagen1.setIcon(new ImageIcon(imgBytes));
            }
            ps2.close();
            rs.close();
            fis.close();
            listo.setText("Foto agregada correctamente");
            subir.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_subirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubirImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubirImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubirImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubirImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubirImagen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel lFondo;
    private javax.swing.JLabel lIDMascota;
    private javax.swing.JLabel listo;
    private javax.swing.JToggleButton subir;
    // End of variables declaration//GEN-END:variables
}
