
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author francisco.perdomo
 */
public class VerMascota extends javax.swing.JFrame {
    BaseDeDatos1 bdd  = new BaseDeDatos1();
    int nroDenuncia = 0;
    
    /**
     *
     */
    public VerMascota() {
        initComponents();
    }

    /**
     *
     * @param datosm
     */
    public VerMascota(String datosm) throws IOException {
        initComponents();
        textoayuda.setText("<html>Si se recuperó la mascota,<br>  ingresa la cédula de quien <br> la fue a buscar y haz click aquí :</html>");
        String[] lista = datosm.split(", ");
        nrochip.setText(lista[0]);
        datos.setText(lista[1]);
        desc.setText(lista[2]);
        fechanac.setText(lista[3]);
        agregarRaza(lista[4]);
        vet.setText(lista[5]);
        subirfoto();
    }
    
    /**
     *
     * @param idraza
     */
    public void agregarRaza(String idraza){
        int idraza1 = Integer.parseInt(idraza);
        String[] nombres = {"Labrador","Husky","Chihuahua","Persa","Siamés","Snowshoe","lolito"};
        raza.setText(nombres[idraza1]);
    }
    /**
     * Metodo encargado de mostrar la foto de la mascota en pantalla cuando se muestra la denuncia.
     */
    public void subirfoto() throws IOException{
        try {
            Connection con = null;
            Class.forName("org.postgresql.Driver").newInstance();
            // Obtiene una conexión a la base de datos
            con = DriverManager.getConnection("jdbc:postgresql://192.168.56.56:5432/Mascotas","postgres","people098");
            if (!con.isClosed()){
                System.out.println("Successfully connected to MySQL server using TCP/IP...");
            } 
            PreparedStatement ps2 = con.prepareStatement("SELECT idimagen FROM imagen WHERE idmascota = "+nrochip.getText());
            ResultSet rs = ps2.executeQuery();
            //boolean hayFoto= rs.next();
            while(rs.next()){
                byte[] blob= rs.getBytes(1);
                if (blob!=null){
                    BufferedImage img = null;
                    img= ImageIO.read(new ByteArrayInputStream(blob));
                    foto.setIcon(new ImageIcon(blob));
                }else{
                    foto.setIcon(new ImageIcon("src/imagenes/catdog.png"));
                    pieFoto.setText("Esta mascota no tiene foto asignada");
                }
            }
            ps2.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(SubirImagen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        ldatos = new javax.swing.JLabel();
        lnrochip = new javax.swing.JLabel();
        lfechanac = new javax.swing.JLabel();
        lraza = new javax.swing.JLabel();
        ldesc = new javax.swing.JLabel();
        lvet = new javax.swing.JLabel();
        datos = new javax.swing.JLabel();
        raza = new javax.swing.JLabel();
        fechanac = new javax.swing.JLabel();
        nrochip = new javax.swing.JLabel();
        vet = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        bresolver = new javax.swing.JButton();
        textoayuda = new javax.swing.JLabel();
        pieFoto = new javax.swing.JLabel();
        ciresponsable = new javax.swing.JTextField();
        lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Fondo.setPreferredSize(new java.awt.Dimension(500, 520));
        Fondo.setVerifyInputWhenFocusTarget(false);
        Fondo.setLayout(null);

        ldatos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ldatos.setForeground(new java.awt.Color(0, 78, 150));
        ldatos.setText("Datos de: ");
        Fondo.add(ldatos);
        ldatos.setBounds(10, 30, 82, 24);

        lnrochip.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lnrochip.setForeground(new java.awt.Color(0, 78, 150));
        lnrochip.setText("Nro Chip: ");
        Fondo.add(lnrochip);
        lnrochip.setBounds(20, 115, 47, 15);

        lfechanac.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lfechanac.setForeground(new java.awt.Color(0, 78, 150));
        lfechanac.setText("Fecha Nac:");
        Fondo.add(lfechanac);
        lfechanac.setBounds(10, 90, 55, 15);

        lraza.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lraza.setForeground(new java.awt.Color(0, 78, 150));
        lraza.setText("Raza: ");
        Fondo.add(lraza);
        lraza.setBounds(39, 65, 31, 15);

        ldesc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        ldesc.setForeground(new java.awt.Color(0, 78, 150));
        ldesc.setText("Descripción: ");
        Fondo.add(ldesc);
        ldesc.setBounds(10, 160, 63, 15);

        lvet.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lvet.setForeground(new java.awt.Color(0, 78, 150));
        lvet.setText("Veterinaria:");
        Fondo.add(lvet);
        lvet.setBounds(10, 140, 56, 15);

        datos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        datos.setForeground(new java.awt.Color(0, 78, 150));
        datos.setText("    ");
        Fondo.add(datos);
        datos.setBounds(105, 33, 120, 21);

        raza.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        raza.setForeground(new java.awt.Color(0, 78, 150));
        raza.setText("    ");
        Fondo.add(raza);
        raza.setBounds(79, 65, 90, 15);

        fechanac.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        fechanac.setForeground(new java.awt.Color(0, 78, 150));
        fechanac.setText("    ");
        Fondo.add(fechanac);
        fechanac.setBounds(79, 90, 90, 15);

        nrochip.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        nrochip.setForeground(new java.awt.Color(0, 78, 150));
        nrochip.setText("    ");
        Fondo.add(nrochip);
        nrochip.setBounds(80, 115, 90, 15);

        vet.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        vet.setForeground(new java.awt.Color(0, 78, 150));
        vet.setText("    ");
        Fondo.add(vet);
        vet.setBounds(89, 140, 90, 15);

        desc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        desc.setForeground(new java.awt.Color(0, 78, 150));
        desc.setText("    ");
        Fondo.add(desc);
        desc.setBounds(89, 160, 80, 15);

        foto.setMaximumSize(new java.awt.Dimension(200, 200));
        foto.setMinimumSize(new java.awt.Dimension(200, 200));
        Fondo.add(foto);
        foto.setBounds(190, 10, 200, 200);

        bresolver.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bresolver.setText("Resolver denuncia");
        bresolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresolverActionPerformed(evt);
            }
        });
        Fondo.add(bresolver);
        bresolver.setBounds(240, 260, 123, 23);

        textoayuda.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        textoayuda.setForeground(new java.awt.Color(0, 78, 150));
        textoayuda.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        textoayuda.setToolTipText("");
        textoayuda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textoayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Fondo.add(textoayuda);
        textoayuda.setBounds(10, 230, 200, 80);

        pieFoto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        pieFoto.setForeground(new java.awt.Color(0, 78, 150));
        pieFoto.setText("      ");
        Fondo.add(pieFoto);
        pieFoto.setBounds(220, 210, 160, 20);

        ciresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciresponsableActionPerformed(evt);
            }
        });
        Fondo.add(ciresponsable);
        ciresponsable.setBounds(240, 290, 137, 20);

        lfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuFondo.jpg"))); // NOI18N
        lfondo.setText("    ");
        Fondo.add(lfondo);
        lfondo.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bresolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresolverActionPerformed
        bdd.enviarConsulta("UPDATE denuncia SET fecharesolucion = '4/11/2017',"
                + "personaresponsable =" + ciresponsable.getText() + "where id_mascota = "+ nrochip.getText()+" and fecharesolucion is null");
        bresolver.setVisible(false);
        textoayuda.setText("Denuncia resuelta");
        ciresponsable.setVisible(false);
    }//GEN-LAST:event_bresolverActionPerformed

    private void ciresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciresponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciresponsableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton bresolver;
    private javax.swing.JTextField ciresponsable;
    private javax.swing.JLabel datos;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel fechanac;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel ldatos;
    private javax.swing.JLabel ldesc;
    private javax.swing.JLabel lfechanac;
    private javax.swing.JLabel lfondo;
    private javax.swing.JLabel lnrochip;
    private javax.swing.JLabel lraza;
    private javax.swing.JLabel lvet;
    private javax.swing.JLabel nrochip;
    private javax.swing.JLabel pieFoto;
    private javax.swing.JLabel raza;
    private javax.swing.JLabel textoayuda;
    private javax.swing.JLabel vet;
    // End of variables declaration//GEN-END:variables
}
